language: generic
services:
  - docker
env:
  - BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
before_install: |
  echo "Updating docker-compose to version 1.24.1" \
  && curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` -o /tmp/docker-compose \
  && sudo rm /usr/local/bin/docker-compose \
  && sudo mv /tmp/docker-compose /usr/local/bin/docker-compose \
  && chmod +x /usr/local/bin/docker-compose \
  && cd $TRAVIS_BUILD_DIR \
  && echo "Creating data directory" \
  && mkdir -p $TRAVIS_BUILD_DIR/data/donations \
  && mkdir -p $TRAVIS_BUILD_DIR/data/quarantine \
  && mkdir -p $TRAVIS_BUILD_DIR/data/unverified_donations \
  && docker-compose -f env/docker/docker-compose.travis.yml build --parallel
script:
  cd $TRAVIS_BUILD_DIR && docker-compose -f env/docker/docker-compose.travis.yml up --abort-on-container-exit --exit-code-from testing
